[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Disable secret scanning for public environment variables
[build.processing]
  skip_processing = false

# Allow public environment variables
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Override Netlify's secret detection for public variables
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "$NEXT_PUBLIC_FIREBASE_API_KEY"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "$NEXT_PUBLIC_FIREBASE_DATABASE_URL"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
  NEXT_PUBLIC_FIREBASE_APP_ID = "$NEXT_PUBLIC_FIREBASE_APP_ID"
  NEXT_PUBLIC_CLOUDINARY_URL = "$NEXT_PUBLIC_CLOUDINARY_URL"
  NEXT_PUBLIC_CLOUDINARY_PRESET = "$NEXT_PUBLIC_CLOUDINARY_PRESET"
